version: '3.8'

services:
  myapp:
    container_name: myapp
    build: .
    restart: always
    ports:
      - "27017:27017"
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - scrapify_net

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: notebooks
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - scrapify_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root 
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - scrapify_net

networks:
  scrapify_net:

volumes:
  postgres:
  pgadmin:
